# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63682f35eebd9f42d145dd20cb8fa93cbab399e220c623e819d73ea6db8cec2990edd875beb5f25f5e0ec9a2da151a886987728cb87f77aec5966a059aae95d6

test:
  secret_key_base: 7c79be9a20a9933b0ac2ad969906a5ec4f8c199ba6ddb7649580eb6ee618c11af9b5dc6b56cf8a9f763d73359dcfc3a6ae853e9eb5db90760e9fc7aa7df30661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
